// Replace this with the public HTTPS URL of your persistent FastAPI backend.
const API_BASE = "https://YOUR-BACKEND-DOMAIN";
let selected = null;
const $ = s => document.querySelector(s);
function token(){ return sessionStorage.getItem('trollControlToken') || ''; }
async function api(path, options={}) { const r=await fetch(API_BASE+path,{...options,headers:{Authorization:`Bearer ${token()}`,...options.headers}}); const j=await r.json().catch(()=>({detail:r.statusText})); if(!r.ok)throw Error(j.detail||'Request failed'); return j; }
$('#token').onclick=()=>{const t=prompt('Enter the Troll Control admin token');if(t){sessionStorage.setItem('trollControlToken',t);load();}};
function result(text, bad=false){$('#result').textContent=text;$('#result').style.color=bad?'#fca5a5':'';}
async function load(){try{const ds=await api('/api/devices'); const box=$('#devices');box.innerHTML='';$('#status').textContent=`${ds.filter(d=>d.online).length} online`;ds.forEach(d=>{const n=$('#card').content.cloneNode(true);const b=n.querySelector('button');b.querySelector('strong').textContent=d.hostname;b.querySelector('span').textContent=`macOS ${d.version||'unknown'}`;const s=b.querySelector('small');s.textContent=d.online?'● Online':'● Offline';s.className=d.online?'online':'offline';b.onclick=()=>select(d);box.append(n);});}catch(e){$('#status').textContent=e.message+' — set the admin token and backend URL.';}}
function select(d){selected=d;$('#panel').innerHTML=`<h2>${d.hostname}</h2><p>macOS ${d.version||'unknown'} · <span class="${d.online?'online':'offline'}">${d.online?'Online':'Offline'}</span></p><input id="file" type="file" accept="image/*"><div class="controls"><button data-c="sound">Play Sound</button><button data-c="calculator">Calculator</button><button data-c="message">Message</button><button data-c="bluetooth">Bluetooth</button><button data-c="shutdown" class="danger">Shutdown</button><button id="unpair" class="danger">Unpair</button></div><p id="result"></p>`;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>run(b.dataset.c));$('#file').onchange=upload;$('#unpair').onclick=unpair;}
async function run(command){if(command==='shutdown'&&!confirm('Send a shutdown request? The Mac user must confirm locally.'))return;try{const r=await api(`/api/devices/${selected.id}/command/${command}`,{method:'POST'});result(r.message||'Command sent',!r.ok);}catch(e){result(e.message,true)}}
async function upload(e){const file=e.target.files[0];if(!file)return;result('Uploading…');try{const f=new FormData();f.append('image',file);const up=await api('/api/wallpaper',{method:'POST',headers:{},body:f});const r=await api(`/api/devices/${selected.id}/wallpaper`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(up)});result(r.message||'Wallpaper applied',!r.ok)}catch(e){result(e.message,true)}}
async function unpair(){if(!confirm(`Unpair ${selected.hostname}?`))return;try{await api(`/api/devices/${selected.id}/unpair`,{method:'POST'});$('#panel').innerHTML='<h2>Unpaired</h2>';load()}catch(e){alert(e.message)}}
load();setInterval(load,10000);
